In [1]:
import dateutil
import pandas as pd

In [2]:
# reading excel
df = pd.read_excel('PET_PNP_INPT_A_EPC0_YIR_MBBL_M.xls',sheet_name = 'Data 1', index_col=0)

In [3]:
# Removing non PADD columns
df = df.loc[:,df.loc['Sourcekey'].str.contains('MCRRIP') | df.loc['Sourcekey'].str.contains('MCRRIUS1')  ]

In [4]:
# setting column name for date 

df = df.rename(columns=df.iloc[1]).drop(df.index[0])
df = df.iloc[1:].reset_index().rename(columns= {'Back to Contents':'Date'})

In [5]:
# removing older data than Jan 2016
df = df[df.Date > dateutil.parser.parse("2016-01-01")]

# extracting month and year 
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year
df['Quarter'] = df['Date'].dt.to_period('Q')

In [6]:
# shortening the column names
df.rename(columns = {'East Coast (PADD 1) Refinery and Blender Net Input of Crude Oil (Thousand Barrels)':'PADD1',
                     'Midwest (PADD 2) Refinery and Blender Net Input of Crude Oil (Thousand Barrels)':'PADD2',
                     'Gulf Coast (PADD 3) Refinery and Blender Net Input of Crude Oil (Thousand Barrels)':'PADD3',
                     'Rocky Mountain (PADD 4) Refinery and Blender Net Input of Crude Oil (Thousand Barrels)':'PADD4', 
                     'West Coast (PADD 5) Refinery and Blender Net Input of Crude Oil (Thousand Barrels)':'PADD5',
                    'U.S. Refinery and Blender Net Input of Crude Oil (Thousand Barrels)':'TotalPADD'
                    }, inplace=True)

# defining methods for shortening

def shorten(obj):
    obj.rename(columns = {'East Coast (PADD 1) Refinery and Blender Net Input of Crude Oil (Thousand Barrels)':'PADD1',
                     'Midwest (PADD 2) Refinery and Blender Net Input of Crude Oil (Thousand Barrels)':'PADD2',
                     'Gulf Coast (PADD 3) Refinery and Blender Net Input of Crude Oil (Thousand Barrels)':'PADD3',
                     'Rocky Mountain (PADD 4) Refinery and Blender Net Input of Crude Oil (Thousand Barrels)':'PADD4', 
                     'West Coast (PADD 5) Refinery and Blender Net Input of Crude Oil (Thousand Barrels)':'PADD5',
                    'Total US Refinery Net Input of Crude Oil':'TotalPADD'
                    }, inplace=True)
    
def unshorten(obj):
    obj.rename(columns = {'PADD1':'(PADD 1) Refinery and Blender Net Input of Crude Oil',
                     'PADD2':'(PADD 2) Refinery and Blender Net Input of Crude Oil',
                    'PADD3': '(PADD 3) Refinery and Blender Net Input of Crude Oil',
                   'PADD4':  '(PADD 4) Refinery and Blender Net Input of Crude Oil', 
                   'PADD5':  '(PADD 5) Refinery and Blender Net Input of Crude Oil',
                  'TotalPADD':  'Total US Refinery Net Input of Crude Oil'
                    }, inplace=True)

In [7]:
# reordering columns

order = [8,9,7,2,3,4,5,6,1] # setting column's order
df = df[[df.columns[i] for i in order]]
df

     Year Quarter  Month  PADD1   PADD2   PADD3  PADD4  PADD5 TotalPADD
420  2016  2016Q1      1  35235  115438  252514  17826  73477    494490
421  2016  2016Q1      2  31685  105169  239811  16681  66096    459442
422  2016  2016Q1      3  32884  105672  267947  18058  73995    498556
423  2016  2016Q2      4  34745  100007  254036  15420  73400    477608
424  2016  2016Q2      5  36690  111828  265512  17826  71485    503341
..    ...     ...    ...    ...     ...     ...    ...    ...       ...
481  2021  2021Q1      2  16567   92328  169170  16233  52161    346459
482  2021  2021Q1      3  20986  112124  232866  17271  62627    445874
483  2021  2021Q2      4  18903  103620  254083  15923  62281    454810
484  2021  2021Q2      5  21682  115634  263201  16650  66275    483442
485  2021  2021Q2      6  21517  122067  258213  16606  67304    485707

[66 rows x 9 columns]

In [8]:
df1 = df.groupby('Quarter')['PADD1', 'PADD2', 'PADD3', 'PADD4', 'PADD5', 'TotalPADD'].sum()

<ipython-input-8-93df6a125ec8>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df1 = df.groupby('Quarter')['PADD1', 'PADD2', 'PADD3', 'PADD4', 'PADD5', 'TotalPADD'].sum()

In [9]:
unshorten(df1)
df1

,(PADD 1) Refinery and Blender Net Input of Crude Oil,(PADD 2) Refinery and Blender Net Input of Crude Oil,(PADD 3) Refinery and Blender Net Input of Crude Oil,(PADD 4) Refinery and Blender Net Input of Crude Oil,(PADD 5) Refinery and Blender Net Input of Crude Oil,Total US Refinery Net Input of Crude Oil
Quarter,,,,,,
2016Q1,99804,326279,760272,52565,213568,1452488
2016Q2,105203,322314,776907,52649,216854,1473927
2016Q3,100175,340274,791942,57856,229599,1519846
2016Q4,100314,336261,786082,55800,199677,1478134
2017Q1,85420,331622,752545,54315,207056,1430958
2017Q2,100160,349713,831389,56889,220498,1558649
2017Q3,101922,354039,776058,60605,234419,1527043
2017Q4,103363,336184,822553,55322,221169,1538591
2018Q1,88711,332538,779174,56939,220047,1477409
2018Q2,103024,361877,818909,54847,220330,1558987
2018Q3,98510,353917,845381,58450,237845,1594103
2018Q4,91306,336889,854258,56092,224788,1563333
2019Q1,81427,328565,779276,55398,213262,1457928
2019Q2,95614,339219,818422,57827,214531,1525613
2019Q3,78311,370514,822419,61898,227584,1560726
2019Q4,71529,349667,803219,54622,222092,1501129
2020Q1,63523,333045,777613,54440,206704,1435325
2020Q2,52512,282886,662818,45603,153391,1197210
2020Q3,51236,330236,679397,54979,174381,1290229
2020Q4,53753,317703,686799,49970,170607,1278832
2021Q1,56063,316919,647525,50836,171268,1242611
2021Q2,62102,341321,775497,49179,195860,1423959

In [10]:
df2 = df.groupby('Year')['PADD1', 'PADD2', 'PADD3', 'PADD4', 'PADD5', 'TotalPADD'].sum()

<ipython-input-10-c38842a14df6>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df2 = df.groupby('Year')['PADD1', 'PADD2', 'PADD3', 'PADD4', 'PADD5', 'TotalPADD'].sum()

In [11]:
unshorten(df2)
df2

,(PADD 1) Refinery and Blender Net Input of Crude Oil,(PADD 2) Refinery and Blender Net Input of Crude Oil,(PADD 3) Refinery and Blender Net Input of Crude Oil,(PADD 4) Refinery and Blender Net Input of Crude Oil,(PADD 5) Refinery and Blender Net Input of Crude Oil,Total US Refinery Net Input of Crude Oil
Year,,,,,,
2016,405496,1325128,3115203,218870,859698,5924395
2017,390865,1371558,3182545,227131,883142,6055241
2018,381551,1385221,3297722,226328,903010,6193832
2019,326881,1387965,3223336,229745,877469,6045396
2020,221024,1263870,2806627,204992,705083,5201596
2021,118165,658240,1423022,100015,367128,2666570

In [12]:
# All units in thousand barrels
unshorten(df)
df.to_csv(r'Monthly.csv', index = False)#,sheet_name = 'Monthly')
df1.to_csv(r'Quarterly.csv')#,sheet_name = 'Quarterly')
df2.to_csv(r'Annual.csv')#,sheet_name = 'Annual')